'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const Phase=require('../../tools/training/nnue-phase-runtime'),Runtime=require('../../tools/training/hybrid-runtime');
const Lazy=require('../../tools/training/hybrid-runtime-lazy'),Baseline=require('./hce-r3-baseline');
const ROOT=path.resolve(__dirname,'../..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'chessy-hybrid-lazy-test-'));
try {
  const evaluator=fs.readFileSync(path.join(ROOT,'experiments/wasm/src/eval.rs'),'utf8');
  const search=fs.readFileSync(path.join(ROOT,'experiments/wasm/src/search.rs'),'utf8');
  const engine=fs.readFileSync(path.join(ROOT,'experiments/wasm/src/engine.rs'));
  const synthetic=Phase.synthetic(8),weights=Baseline.baselineCenter(Baseline.parseRustEvaluator(evaluator));
  const original=Runtime.render(evaluator,{model:synthetic.model||require('./h4-v3-reference').loadModel(synthetic.bytes,synthetic.metadata),weights,config:Runtime.CONFIGS[5]},'hybrid');
  const patched=Lazy.patchEvaluator(original),patchedSearch=Lazy.patchSearch(search);
  assert(patched.includes('pub(crate) fn evaluate_original(position: &Position)'));
  assert(patched.includes('fn evaluate_neural_cached(position: &Position, nnue_acc: [[i32; NNUE_H]; 2])'));
  const cached=patched.slice(patched.indexOf('fn evaluate_neural_cached('),patched.indexOf('// Search-owned'));
  assert(!cached.includes('nnue_add_piece('));assert(cached.includes('nnue_finish(nnue_acc, position.turn, phase)'));
  assert(!patched.includes('{{'));assert(patched.includes('stack.enter(path.len(), mv)'));
  assert.equal((patchedSearch.match(/lazy\.enter\(/g)||[]).length,4);
  assert.equal((patchedSearch.match(/let mut lazy_state/g)||[]).length,3);
  assert(patchedSearch.includes('return quiesce_node(position, lazy, alpha_initial, beta_initial, ply, 0);'));
  assert(patchedSearch.includes('lazy.enter(ply + 1, mv);\n        let mut score;'));
  assert(patchedSearch.includes('lazy.enter(1, root_move);'));
  // A missing search boundary or extra evaluator site must fail closed.
  assert.throws(()=>Lazy.patchSearch(search.replace('        let mut score;\n        let mut child_rep;','        let mut score;\n        let child_rep;')),/anchor/);
  assert.throws(()=>Lazy.patchSearch(search+'\nfn unexpected(position: &Position) { eval::evaluate(position); }'),/three leaf/);
  assert.throws(()=>Lazy.patchEvaluator(original.replace('        nnue_add_piece(&mut nnue_acc, piece, square);','')),/anchor/);
  assert(fs.readFileSync(path.join(ROOT,'experiments/wasm/src/engine.rs')).equals(engine));
  assert.equal(Lazy.PLAN.expectedRecords,576);assert.equal(Lazy.PLAN.pvEqualityRequired,false);
  assert.equal(Lazy.PLAN.followupGamesAllowed,false);assert.deepEqual(Lazy.PLAN.configurations,['original','lazy']);
  const summary={};for(const stage of ['all','opening','middlegame','endgame'])summary[stage]={lazy:{original:{nodes16384:{pairedMedianNpsRatio:1.05}}}};
  assert.equal(Lazy.select(summary,true,true,true).selected,'lazy');
  assert.equal(Lazy.select(summary,false,true,true).eligible,false);
  assert.equal(Lazy.select(summary,true,false,true).eligible,false);
  assert.equal(Lazy.select(summary,true,true,false).eligible,false);
  summary.opening.lazy.original.nodes16384.pairedMedianNpsRatio=0.949999;
  assert.equal(Lazy.select(summary,true,true,true).eligible,false);
  summary.opening.lazy.original.nodes16384.pairedMedianNpsRatio=0.95;
  assert.equal(Lazy.select(summary,true,true,true).eligible,true);
  summary.all.lazy.original.nodes16384.pairedMedianNpsRatio=1.049999;
  assert.equal(Lazy.select(summary,true,true,true).eligible,false);
  summary.all.lazy.original.nodes16384.pairedMedianNpsRatio=NaN;
  assert.throws(()=>Lazy.select(summary,true,true,true),/invalid lazy selection/);
  const evidence=path.join(tmp,'evidence.json'),bytes=Buffer.from('{"complete":true}\n');
  Lazy.atomicNew(evidence,bytes);assert(fs.readFileSync(evidence).equals(bytes));
  assert.throws(()=>Lazy.atomicNew(evidence,Buffer.from('overwrite')),/EEXIST/);
  assert(fs.readFileSync(evidence).equals(bytes));
  assert.throws(()=>Lazy.prepare(path.join(ROOT,'unsafe-lazy-output'),'unused'),/outside a Git checkout/);
}finally{fs.rmSync(tmp,{recursive:true,force:true});}
console.log('PASS: lazy search ownership, fail-closed patch closure, exact selection boundaries and immutable evidence publication');
